name: 'action-setup-nvim-lua'
description: 'Setup lua for testing neovim plugin'
inputs:
  luarocks-version:
    description: 'luarocks version (minimum: 3.11.1)'
    required: false
    default: '3.11.1'

outputs:
  luajit:
    description: 'lua executable path'
  luarocks:
    description: 'luarocks executable path'

runs:
  using: 'node20'
  main: 'src/index.js'
