# for local test

services:
  node:
    image: "node:20"
    user: "node"
    command: "tail -f"
    working_dir: /home/node/app
    environment:
        RUNNER_TEMP: /tmp
        INPUT_LUAROCKS-VERSION: 3.11.1
    volumes:
        - "./:/home/node/app"
